# rule identifiers to exclude from running
disabled_rules:
- trailing_whitespace
- todo

# some rules are only opt-in
opt_in_rules:
- force_unwrapping

# paths to ignore during linting. Takes precedence over `included`.
excluded:
- DiscoverMoviesTest
- DiscoverMoviesUITests
- TMDbMovieKitTests
- Pods

# Configure rules
line_length: 300
type_body_length: 300
