# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools

# Update fastlane automatically
update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    # Make sure we have the required certificates
    cert
    # Make sure we have the requried provisioning Profiles
    sigh(force: true)
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
